name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

env:
  dotnet_version: 6.0.x
  build_config: Release

jobs:
  ci:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet_version }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Code format
      run: dotnet csharpier --check .
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Publish
      if: github.repository == 'protyposis/AudioAlign' && startsWith(github.ref, 'refs/tags/v')
      run: |
        dotnet publish ./AudioAlign/ -c ${{ env.build_config }} -o dist --no-restore --no-build
        7z a AudioAlign-${{ env.build_config }}-${{ github.ref_name }}.zip ./dist/*
    - name: GitHub Release
      if: github.repository == 'protyposis/AudioAlign' && startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        draft: true # create draft release because changelog needs to be added manually (and could be too easily forgotten otherwise)
        files: ./AudioAlign*.zip
